### ISSUE TITLE
Automatically tag imported raw entities with their source federation, based on MDRPI

### ISSUE THREAD

**Issue by smangelsdorf** [ausaccessfed/saml-service#174]
Tag entities based on their source federation.

It's probably useful to have the tags / identifiers configurable, for example:

```yaml
federation_tags:
  - registration_authority: https://aaf.edu.au
    tag: aaf
  - registration_authority: http://otherfederation.example.edu
    tag: example
```

Registration info can (unsurprisingly) be sourced from the `RegistrationInfo` extension defined in MDRPI:

```xml
<EntityDescriptor entityID="https://vho.aaf.edu.au/idp/shibboleth">
  <Extensions>
    <mdrpi:RegistrationInfo registrationAuthority="https://aaf.edu.au" registrationInstant="2010-12-06T12:35:21Z">
      <mdrpi:RegistrationPolicy xml:lang="en">http://aaf.edu.au</mdrpi:RegistrationPolicy>
    </mdrpi:RegistrationInfo>
  </Extensions>
  ...
</EntityDescriptor>
```
